<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
شکلات‌های خوب‌تر
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
فرض کنید که بعد از میل کردن چند شکلات معمولی (غیر دارک) متوجه شده‌ایم که بسیاری از آن‌ها هم خوشمزه هستند و اگر بتوانیم موارد با کیفیت‌تر آن‌ها را پیدا کنیم احتمالاً فروش خوبی خواهند داشت. پس در گام آخر از پروژه می‌خواهیم شرکت‌هایی که شکلات‌های باکیفیت‌تری را تولید می‌کنند شناسایی کرده و شکلات‌های ‌‌آن‌ها را جدا کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در گام پیشین قیمت شکلات‌ها را تخمین زده و دیتافریم نهایی را در فایلی به نام <code>chocolate_price.csv</code> ذخیره کردید. در ابتدا آن فایل را به شکل یک دیتافریم بخوانید.
</font>
</p>

In [54]:
import numpy as np
import pandas as pd

df = pd.read_csv('chocolate_price.csv')
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
توجه داشته باشید که در این گام تنها با شکلات‌های غیرتلخ کار داریم. پس در ابتدا تنها شکلات‌هایی که درصد کاکائوی آن‌ها کمتر یا مساوی  ۷۰ درصد است را جدا کرده و در دیتافریم <code>df</code> ذخیره کنید.
</font>
</p>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از جداسازی و ساخت دیتافریم، به کمک تابع <code dir=ltr>reset_index()</code> نمایه‌ها را ریست کنید. در این مرحله به آرگومان‌های <code>inplace</code> و <code>drop</code> هم توجه کنید.
</font>
</p>

In [55]:
df = df[df['Cocoa Percent'] <= 70.0]
df.reset_index(inplace=True,drop=True)
df

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0
...,...,...,...,...,...,...,...,...,...
995,Zotter,Peru,2011,70.0,Austria,75.0,Blend,Peru,131250.0
996,Zotter,Congo,2011,65.0,Austria,60.0,Forastero,Congo,97500.0
997,Zotter,Kerala State,2011,65.0,Austria,70.0,Forastero,India,113750.0
998,Zotter,Kerala State,2011,62.0,Austria,65.0,Blend,India,100750.0
999,Zotter,"Brazil, Mitzi Blue",2010,65.0,Austria,60.0,Blend,Brazil,97500.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این قسمت به ازای هر شرکت شکلات‌سازی، میانگین امتیاز شکلات‌های آن را برای هر سال محاسبه کرده و همچون جدول زیر در دیتافریم <code>companies</code> ذخیره کنید.

<center>

| | 2006 | ... | 2015 | 2016 | 2017 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| A. Morin | NaN | ... | 63.75 | 75.0 | NaN |
| ... | ... | ... | ... | ... | ...  |
| hexx | NaN | ... | 60.00 | NaN | NaN |
| twenty-four blackbirds | NaN | ... | NaN | NaN | NaN |

</center>
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از استفاده از دستور <code>groupby</code> و محاسبه‌ی میانگین از دستور <code>unstack</code> استفاده کنید.
</font>
</p>

In [56]:
companies = df.groupby(['Company','Review Date'])['Rating'].mean()
companies = companies.unstack()

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
خطوط زیر برای استانداردسازی شکل جدول اعمال می‌شوند. این خطوط را تغییر نداده و تنها سلول زیر را اجرا کنید.
</font>
</p>

In [57]:
companies.columns.name = None
companies.index.name = None
companies

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
A. Morin,NaN,NaN,NaN,NaN,NaN,NaN,72.500000,66.363636,70.0,63.75,75.0,NaN
AMMA,NaN,NaN,NaN,NaN,77.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acalli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN
Adi,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN
Aequare (Gianduja),NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Zokoko,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,65.0,NaN
Zotter,NaN,NaN,NaN,NaN,60.0,67.5,69.285714,NaN,NaN,NaN,NaN,NaN
hello cocoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.00,NaN,NaN
hexx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.00,NaN,NaN
twenty-four blackbirds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت سوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
برای پیدا کردن بهترین شرکت‌ها می‌خواهیم تنها امتیاز سال‌های ۲۰۱۲ به بعد را در نظر بگیریم (خود سال ۲۰۱۲ را هم در نظر بگیرید).
ابتدا به ازای هر کمپانی، میانگین امتیاز سال‌های ۲۰۱۲ به بعد آن را محاسبه کرده و در متغیر <code>mean_ratings</code> ذخیره کنید.
توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>

In [58]:
mean_ratings = companies[[2012,2013,2014,2015,2016,2017]].mean(axis=1)
mean_ratings

A. Morin                  69.522727
AMMA                            NaN
Acalli                    75.000000
Adi                             NaN
Aequare (Gianduja)              NaN
                            ...
Zokoko                    65.000000
Zotter                    69.285714
hello cocoa               55.000000
hexx                      60.000000
twenty-four blackbirds    65.000000
Length: 313, dtype: float64

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
اکنون به کمک میانگین امتیاز هر کمپانی (<code>mean_ratings</code>)، ۱۰ کمپانی با بهترین امتیاز را پیدا کنید و در متغیر <code>best_ratings</code> ذخیره کنید. توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:purple"><b>توجه:</b></span>
در مواردی که امتیاز کمپانی‌ها یکسان باشد، باید کمپانی را براساس ترتیب حروف الفبا انتخاب کنید. به‌عنوان مثال اگر دو کمپانی <code>A</code> و <code>B</code> هر دو میانگین امتیاز <code>75.00</code> داشته باشند، اولویت با شرکت <code>A</code> است.
</font>
</p>

In [59]:
mean_ratings1 = mean_ratings.copy()
print(type(mean_ratings1))
mean_ratings1=mean_ratings1.reset_index()
print(type(mean_ratings1))
best_ratings = mean_ratings1.sort_values(by =[0,'index'] ,ascending=[False,True])
best_ratings = best_ratings.set_index('index' ).squeeze().head(10)
best_ratings

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

index
Patric                     80.000000
Tobago Estate (Pralus)     80.000000
Willie's Cacao             80.000000
L.A. Burdick (Felchlin)    77.500000
Matale                     77.500000
Pacari                     77.500000
Valrhona                   76.666667
Acalli                     75.000000
Amedei                     75.000000
Askinosie                  75.000000
Name: 0, dtype: float64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت چهارم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
اکنون شکلات‌هایی که کمپانی سازنده‌شان جزو ۱۰ شرکت برتر (<code>best_ratings</code>) است را از دیتافریم <code>df</code> انتخاب کرده و در دیتافریم <code>chocolates_to_sell</code> ذخیره کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی ۱:</b></span>
بعد از انتخاب این شکلات‌ها، به‌کمک دستور <code>reset_index</code> نمایه‌ها را ریست کنید. استفاده از آرگومان <code>drop</code> را نیز فراموش نکنید.

<br>
<span style="color:green"><b>راهنمایی ۲:</b></span>
برای بررسی وجود یک متغیر در یک لیست می‌توانید از تابع <code>isin</code> استفاده کنید.
</font>
</p>

In [ ]:
index_column = df['Company']
data_column = df['price(100g)']  
your_series = pd.Series(data_column.values, index=index_column)
your_series

In [60]:
chocolates_to_sell = df[df['Company'].isin(best_ratings.index)]
chocolates_to_sell = chocolates_to_sell.reset_index(drop='index')
chocolates_to_sell

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,Acalli,"Chulucanas, El Platanal",2015,70.0,U.S.A.,75.0,Blend,Peru,131250.0
1,Acalli,"Tumbes, Norandino",2015,70.0,U.S.A.,75.0,Criollo,Peru,131250.0
2,Amedei,"Piura, Blanco de Criollo",2012,70.0,Italy,75.0,Blend,Peru,131250.0
3,Amedei,Porcelana,2007,70.0,Italy,80.0,Criollo (Porcelana),Venezuela,140000.0
4,Amedei,Chuao,2007,70.0,Italy,100.0,Trinitario,Venezuela,175000.0
5,Amedei,Ecuador,2007,70.0,Italy,60.0,Trinitario,Ecuador,105000.0
6,Amedei,Jamaica,2007,70.0,Italy,60.0,Trinitario,Jamaica,105000.0
7,Amedei,Grenada,2007,70.0,Italy,70.0,Trinitario,Grenada,122500.0
8,Amedei,Venezuela,2007,70.0,Italy,75.0,Trinitario (85% Criollo),Venezuela,131250.0
9,Amedei,Madagascar,2007,70.0,Italy,80.0,Trinitario (85% Criollo),Madagascar,140000.0
10,Amedei,Trinidad,2007,70.0,Italy,70.0,Trinitario,Trinidad,122500.0
11,Amedei,Toscano Black,2007,63.0,Italy,70.0,Blend,Other,110250.0
12,Amedei,Toscano Black,2006,70.0,Italy,100.0,Blend,Other,175000.0
13,Amedei,Toscano Black,2006,66.0,Italy,80.0,Blend,Other,132000.0
14,Askinosie,Mababa,2016,68.0,U.S.A.,75.0,Trinitario,Tanzania,127500.0
15,Askinosie,Cortes,2011,70.0,U.S.A.,75.0,Trinitario,Honduras,131250.0
16,Askinosie,San Jose del Tambo,2007,70.0,U.S.A.,60.0,Forastero (Arriba),Ecuador,105000.0
17,L.A. Burdick (Felchlin),Brazil,2012,70.0,U.S.A.,80.0,Blend,Brazil,140000.0
18,L.A. Burdick (Felchlin),Chuao,2012,68.0,U.S.A.,75.0,Trinitario,Venezuela,127500.0
19,L.A. Burdick (Felchlin),Madagascar,2009,64.0,U.S.A.,70.0,Trinitario,Madagascar,112000.0
20,L.A. Burdick (Felchlin),Bolivian,2009,68.0,U.S.A.,60.0,Blend,Bolivia,102000.0
21,Matale,"Somia, 2013",2013,68.0,Australia,80.0,Trinitario,Madagascar,136000.0
22,Matale,Blend,2013,70.0,Australia,75.0,Trinitario,"PNG, Vanuatu, Mad",131250.0
23,Pacari,"Sierra Nevada, Tutu Iku",2016,70.0,Ecuador,80.0,Blend,Colombia,140000.0
24,Pacari,Garaua,2014,70.0,Ecuador,65.0,Blend,Ecuador,113750.0
25,Pacari,Cumbia,2014,70.0,Ecuador,70.0,Blend,Ecuador,122500.0
26,Pacari,Montubia,2014,70.0,Ecuador,75.0,Blend,Ecuador,131250.0
27,Pacari,Tangara,2014,70.0,Ecuador,80.0,Blend,Ecuador,140000.0
28,Pacari,Piura,2012,70.0,Ecuador,80.0,Blend,Peru,140000.0
29,Pacari,Nube- prototype,2011,70.0,Ecuador,70.0,Blend,Ecuador,122500.0
30,Pacari,Esmeraldas,2008,60.0,Ecuador,50.0,Forastero (Arriba),Ecuador,75000.0
31,Pacari,Manabi,2008,65.0,Ecuador,55.0,Forastero (Arriba),Ecuador,89375.0
32,Pacari,Raw,2008,70.0,Ecuador,70.0,Forastero (Arriba),Ecuador,122500.0
33,Patric,Signature Blend,2011,70.0,U.S.A.,75.0,Blend,Other,131250.0
34,Patric,Madagascar,2009,67.0,U.S.A.,70.0,Trinitario,Madagascar,117250.0
35,Patric,"Rio Caribe, Paria Penninsula",2009,70.0,U.S.A.,70.0,Trinitario,Venezuela,122500.0
36,Patric,Madagascar,2007,70.0,U.S.A.,80.0,Trinitario,Madagascar,140000.0
37,Patric,"Piura, Choc. Garage Exclusive",2013,67.0,U.S.A.,80.0,Blend,Peru,134000.0
38,Tobago Estate (Pralus),"Roxborough, Tobago",2012,70.0,France,80.0,Trinitario,Tobago,140000.0
39,Valrhona,"Piura, Illanka, Quemazon",2015,63.0,France,80.0,Blend,Peru,126000.0
40,Valrhona,"Andoa, Grand Cru blend",2013,70.0,France,70.0,Blend,Other,122500.0
41,Valrhona,"Loma Sotavento, 2013",2013,64.0,France,70.0,Blend,Dominican Republic,112000.0
42,Valrhona,"Otucan, Grand Cru",2012,69.0,France,80.0,Blend,Venezuela,138000.0
43,Valrhona,Caraque,2011,56.0,France,65.0,Blend,Other,91000.0
44,Valrhona,"Porcelana, Pedegral",2011,64.0,France,80.0,Criollo,Venezuela,128000.0
45,Valrhona,Tainori,2009,64.0,France,75.0,Blend,Dominican Republic,120000.0
46,Valrhona,Alpaco,2009,66.0,France,75.0,Blend,Ecuador,123750.0
47,Valrhona,Nyangbo,2009,68.0,France,70.0,Forastero,Ghana,119000.0
48,Valrhona,Chuao 2002 P.,2007,65.0,France,75.0,Trinitario,Venezuela,121875.0
49,Valrhona,Manjari,2007,64.0,France,80.0,"Criollo, Trinitario",Madagascar,128000.0
50,Valrhona,"Porcelana, Maracaibo, Palmira P. 2006",2007,64.0,France,65.0,Criollo (Porcelana),Venezuela,104000.0
51,Valrhona,Caraibe,2006,66.0,France,60.0,Trinitario,Carribean,99000.0
52,Valrhona,Guanaja,2006,70.0,France,80.0,"Criollo, Trinitario",South America,140000.0
53,Valrhona,Gran Couva 2005 P.,2006,64.0,France,50.0,Trinitario,Trinidad,80000.0
54,Valrhona,"Porcelana, Maracaibo, Palmira P. 2005",2006,64.0,France,60.0,Criollo (Porcelana),Venezuela,96000.0
55,Valrhona,"Sambirano, Ampamakia 2005, Millot P.",2006,64.0,France,70.0,Trinitario,Madagascar,112000.0
56,Willie's Cacao,Los Llanos,2016,70.0,U.K.,80.0,Blend,Colombia,140000.0
57,Willie's Cacao,Java,2010,69.0,U.K.,75.0,Blend,Indonesia,129375.0
58,Willie's Cacao,San Martin,2009,70.0,U.K.,60.0,Blend,Peru,105000.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت پنجم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در نهایت مجموع قیمت این شکلات‌ها (<code>chocolates_to_sell</code>) را در متغیر <code>priceSum</code> ذخیره کنید تا مجموع دریافتی ما از این شکلات‌ها هم مشخص شود.
</font>
</p>

In [68]:
priceSum = chocolates_to_sell['price(100g)'].sum()
print(priceSum)

7282125.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [69]:
import zlib
import zipfile

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

df.to_csv('normal_chocolates.csv', index = True)
companies.to_csv('companies.csv', index = True)
chocolates_to_sell.to_csv('chocolates_to_sell.csv', index = True)
mean_ratings.to_csv("mean_ratings.csv", index = True)
best_ratings.to_csv("best_ratings.csv", index = True)

np.savez("answers.npz" ,priceSum = priceSum)
file_names = ["answers.npz", "project1_step3.ipynb", "chocolates_to_sell.csv", 
              "companies.csv", "mean_ratings.csv", "best_ratings.csv", "normal_chocolates.csv"]
compress(file_names)

File Paths:
['answers.npz', 'project1_step3.ipynb', 'chocolates_to_sell.csv', 'companies.csv', 'mean_ratings.csv', 'best_ratings.csv', 'normal_chocolates.csv']