<h1 align=center style="direction: rtl;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ماندن یا نماندن؛ مسئله این است!
</font>
</h1>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    توضیحات ابتدایی
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در درسنامه‌های گذشته با حذف مقادیر از داده و مدیریت مقادیر گم‌شده آشنا شدیم. حال در این تمرین قصد داریم با تمرین و کد زدن مهارت خود را به چالش بکشیم! این تمرین در دو بخش آماده شده‌ است: بخش اول به منظور پیش‌پردازش و بخش دوم برای پاسخ‌دهی به تعدادی سوال تحلیلی از داده طراحی شده‌ است.    
    <br>
    فایل 
    <code>migration_rate.csv</code>
    آمار «مهاجرت به» و «مهاجرت از» کشور‌های مختلف را از سال ۱۹۹۰ تا ۲۰۲۰ نشان می‌دهد. هدف این تمرین، تحلیل نرخ مهاجرت تعدادی از کشورهای موجود در این فایل است. در سلول زیر، توضیحات ستون‌های متفاوت این مجموعه‌داده را مشاهده می‌کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<center>

| نام ستون| توضیح ستون|
|:------------------:|:------------------:|
| Country | نام کشور |
| 1990   | در این ستون نرخ مهاجرت هر کشور در سال ۱۹۹۰ آمده‌ است.|
| 1995   |در این ستون نرخ مهاجرت هر کشور در سال ۱۹۹۵ آمده‌ است.|
| 2000   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۰۰ آمده‌ است.|
| 2005   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۰۵ آمده‌ است.|
| 2010   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۱۰ آمده‌ است.|
| 2015   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۱۵ آمده‌ است.|
| 2020   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۲۰ آمده‌ است.|

</center>
</font>
</div>


<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    فرمول محاسبه‌ی نرخ مهاجرت
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    نرخ مهاجرت حاصل نسبت تفاوت مهاجران به کشور و مهاجران از کشور، به جمعیت کشور در آن سال به ازای هر ۱۰۰۰ نفر است. به فرمول زیر توجه کنید.
    </font>
</p>

##### $$\frac{(\text{migration in} - \text{migration out}) * 1000 }{population}$$

<p dir=rtl style="direction:trl; text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    این فرمول در حل مسئله هیچ تاثیری ندارد، بلکه فقط برای درک بهتر آورده شده‌ است. 
</font>
</p>

In [50]:
import numpy as np
import pandas as pd

In [51]:
# TODO: read csv file in df
df = pd.read_csv('migration_rate.csv')
df
df.head(30)

                  Country  1990  1995  2000  2005  2010  2015  2020
0           United States   2.7   3.5   6.5   3.7   3.6   3.2   2.9
1                   India   0.0   NaN  -0.1  -0.3  -0.4  -0.4  -0.4
2      Russian Federation   1.2   3.4   3.2   2.5   3.2   2.5   1.3
3                 Germany   4.3   6.6   1.8   NaN   0.1   4.8   6.6
4                 Algeria  -0.8  -0.9  -1.1  -1.3   NaN  -0.8  -0.2
5              Kazakhstan  -8.4   NaN -16.4   0.6  -0.4   1.9  -1.0
6                   Haiti  -4.0  -3.8  -3.6  -3.2   NaN  -2.9  -3.2
7               Nicaragua  -7.6   NaN  -6.0  -6.6  -5.5  -4.5  -3.3
8                 Burundi  -7.1   NaN -14.7  -0.7   0.7  -1.5   0.2
9         Solomon Islands  -5.8  -4.0  -2.7  -3.8  -5.7  -2.8  -2.5
10           Sierra Leone   3.1 -20.9  -6.8  19.6   2.0  -0.6  -0.6
11                Belgium   0.9   2.1   1.0   4.2   5.5   4.7   4.2
12      Equatorial Guinea  10.4   8.7  12.7  14.8  18.9  17.0  12.4
13                  Nepal  -2.4   0.8  -4.1  -6.2  -7.4 -15.1   1.5
14               Botswana   7.9   3.5   4.7   3.1   2.8  -7.1   1.3
15                  Tonga -22.8 -23.0 -17.4 -15.8 -15.2 -25.4  -7.7
16               Cambodia  -1.9   8.3   6.1  -0.6  -4.3  -2.0  -1.9
17             Uzbekistan  -3.7  -3.0  -2.0  -1.9  -1.0  -0.4  -0.3
18                 Rwanda   0.9 -41.9  36.2  -1.7  -1.7  -2.0  -0.7
19      Brunei Darussalam   3.0   3.4   2.7   0.2  -1.2  -0.4   0.0
20                   Chad   0.1  -0.3   1.8   4.7   1.4   1.5   0.1
21                 Bhutan   0.6   NaN   0.1   2.0  -3.3   0.1   0.4
22                Lebanon  -9.4  24.6  -1.6  25.8  -1.1  41.5  -4.5
23               Pakistan   0.3  -1.8   0.7  -0.9  -0.4   NaN  -1.1
24             Cabo Verde -17.1  -3.5  -2.7  -4.4  -4.7  -3.2  -2.5
25                  Spain  -0.3   1.6   4.6  13.7  10.0  -2.2   0.9
26                 France   1.0   0.4   0.7   3.1   1.4   1.3   0.6
27                Somalia -11.8 -22.3   0.0   0.0  -3.6  -3.6  -2.7
28                 Brazil   0.0   0.0   0.0   0.0   0.0   0.0   0.1
29  Saint Kitts and Nevis   NaN   NaN   NaN   NaN   NaN   NaN   NaN


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش اول : پیش‌پردازش
</font>
</h2>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پیش از تحلیل باید مقادیر گم‌شده در مجموعه‌داده را مدیریت کنید و برخی از اطلاعات را نیز از بین ببرید.
<br>
در گام پیش‌پردازش به ترتیب مراحل زیر را انجام دهید.
<ul>
    <li>
کشورهایی که نرخ مهاجرت آن‌ها در هر ۷ سال گم‌شده است (برای هیچ سالی نرخ مهاجرت آن‌ها ثبت نشده) را برای همیشه از مجموعه‌داده حذف کنید.
    </li>
    <li>
مقادیر گم‌شده کشور‌هایی که اطلاعات برخی از سال‌ها را از دست داده‌اند را با میانگین آن کشور پر کنید. به‌عنوان مثال اگر نرخ مهاجرت کشوری از سال ۱۹۹۵ تا ۲۰۲۰ به ترتیب 
<code>5.2-</code>
، 
<code>3.4-</code>
، 
<code>0.7-</code>
، 
<code>0.9</code>
، 
<code>1.3</code>
 و 
 <code>2.5</code>
  باشد، نرخ مهاجرت سال ۱۹۹۰ که گم‌شده بود را باید با عدد 
<code>0.76-</code>
   پر کنید.
    </li>
</ul>
    </font>
</div>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
گام اول پیش‌پردازش
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
کشورهایی که نرخ مهاجرت آن‌ها در هر ۷ سال گم‌شده است (برای هیچ سالی نرخ مهاجرت آن‌ها ثبت نشده) را برای همیشه از مجموعه‌داده حذف کنید.
</font>
</div>

In [53]:
# TODO: drop some rows
df.dropna(thresh=2,inplace=True)

df.head(30)

               Country  1990  1995  2000  2005  2010  2015  2020
0        United States   2.7   3.5   6.5   3.7   3.6   3.2   2.9
1                India   0.0   NaN  -0.1  -0.3  -0.4  -0.4  -0.4
2   Russian Federation   1.2   3.4   3.2   2.5   3.2   2.5   1.3
3              Germany   4.3   6.6   1.8   NaN   0.1   4.8   6.6
4              Algeria  -0.8  -0.9  -1.1  -1.3   NaN  -0.8  -0.2
5           Kazakhstan  -8.4   NaN -16.4   0.6  -0.4   1.9  -1.0
6                Haiti  -4.0  -3.8  -3.6  -3.2   NaN  -2.9  -3.2
7            Nicaragua  -7.6   NaN  -6.0  -6.6  -5.5  -4.5  -3.3
8              Burundi  -7.1   NaN -14.7  -0.7   0.7  -1.5   0.2
9      Solomon Islands  -5.8  -4.0  -2.7  -3.8  -5.7  -2.8  -2.5
10        Sierra Leone   3.1 -20.9  -6.8  19.6   2.0  -0.6  -0.6
11             Belgium   0.9   2.1   1.0   4.2   5.5   4.7   4.2
12   Equatorial Guinea  10.4   8.7  12.7  14.8  18.9  17.0  12.4
13               Nepal  -2.4   0.8  -4.1  -6.2  -7.4 -15.1   1.5
14            Botswana   7.9   3.5   4.7   3.1   2.8  -7.1   1.3
15               Tonga -22.8 -23.0 -17.4 -15.8 -15.2 -25.4  -7.7
16            Cambodia  -1.9   8.3   6.1  -0.6  -4.3  -2.0  -1.9
17          Uzbekistan  -3.7  -3.0  -2.0  -1.9  -1.0  -0.4  -0.3
18              Rwanda   0.9 -41.9  36.2  -1.7  -1.7  -2.0  -0.7
19   Brunei Darussalam   3.0   3.4   2.7   0.2  -1.2  -0.4   0.0
20                Chad   0.1  -0.3   1.8   4.7   1.4   1.5   0.1
21              Bhutan   0.6   NaN   0.1   2.0  -3.3   0.1   0.4
22             Lebanon  -9.4  24.6  -1.6  25.8  -1.1  41.5  -4.5
23            Pakistan   0.3  -1.8   0.7  -0.9  -0.4   NaN  -1.1
24          Cabo Verde -17.1  -3.5  -2.7  -4.4  -4.7  -3.2  -2.5
25               Spain  -0.3   1.6   4.6  13.7  10.0  -2.2   0.9
26              France   1.0   0.4   0.7   3.1   1.4   1.3   0.6
27             Somalia -11.8 -22.3   0.0   0.0  -3.6  -3.6  -2.7
28              Brazil   0.0   0.0   0.0   0.0   0.0   0.0   0.1
30            Ethiopia   3.5   5.6  -0.5  -0.4  -0.1   0.8   0.3

In [46]:
row_means = df.drop(['Country'],axis=1).apply(lambda x: x.mean(), axis=1)
row_means.isna().iloc[20:50]

20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
dtype: bool

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
گام دوم پیش‌پردازش
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
مقادیر گم‌شده کشور‌هایی که اطلاعات برخی از سال‌ها را از دست داده‌اند را با میانگین آن کشور پر کنید. به‌عنوان مثال اگر نرخ مهاجرت کشوری از سال ۱۹۹۵ تا ۲۰۲۰ به ترتیب 5.2-، 3.4-، 0.7-، 0.9، 1.3 و 2.5 باشد، نرخ مهاجرت سال ۱۹۹۰ که گم‌شده بود را باید با عدد 0.76- پر کنید.
</font>
</div>

In [47]:
# TODO: fill null values of rows
row_means = df.drop(['Country'],axis=1).apply(lambda x: x.mean(), axis=1).astype('float64')
print(df)
df= df.apply(lambda row: row.fillna(row_means[row.name]), axis=1)
print(df)
# df.iloc[:, 1:] = df.iloc[:, 1:].round(1)
df

                Country  1990  1995  2000  2005  2010  2015  2020
0         United States   2.7   3.5   6.5   3.7   3.6   3.2   2.9
1                 India   0.0   NaN  -0.1  -0.3  -0.4  -0.4  -0.4
2    Russian Federation   1.2   3.4   3.2   2.5   3.2   2.5   1.3
3               Germany   4.3   6.6   1.8   NaN   0.1   4.8   6.6
4               Algeria  -0.8  -0.9  -1.1  -1.3   NaN  -0.8  -0.2
..                  ...   ...   ...   ...   ...   ...   ...   ...
186                Mali -12.1  -3.8  -2.8  -1.1  -1.4  -3.7  -2.1
187          Costa Rica   1.2   4.2   4.8   2.0   1.4   0.8   0.8
188              Norway   1.8   2.2   2.7   3.0   6.9   8.8   5.3
189          Tajikistan  -1.3   NaN  -7.9  -4.5  -4.1  -3.4  -2.2
190              Angola   3.5   2.2   2.6   2.9   3.3   1.3   0.2

[185 rows x 8 columns]
                Country  1990      1995  2000      2005  2010  2015  2020
0         United States   2.7  3.500000   6.5  3.700000  3.60   3.2   2.9
1                 India   0.0 -0.266667  -0.1 -0.300000 -0.40  -0.4  -0.4
2    Russian Federation   1.2  3.400000   3.2  2.500000  3.20   2.5   1.3
3               Germany   4.3  6.600000   1.8  4.033333  0.10   4.8   6.6
4               Algeria  -0.8 -0.900000  -1.1 -1.300000 -0.85  -0.8  -0.2
..                  ...   ...       ...   ...       ...   ...   ...   ...
186                Mali -12.1 -3.800000  -2.8 -1.100000 -1.40  -3.7  -2.1
187          Costa Rica   1.2  4.200000   4.8  2.000000  1.40   0.8   0.8
188              Norway   1.8  2.200000   2.7  3.000000  6.90   8.8   5.3
189          Tajikistan  -1.3 -3.900000  -7.9 -4.500000 -4.10  -3.4  -2.2
190              Angola   3.5  2.200000   2.6  2.900000  3.30   1.3   0.2

[185 rows x 8 columns]

                Country  1990      1995  2000      2005  2010  2015  2020
0         United States   2.7  3.500000   6.5  3.700000  3.60   3.2   2.9
1                 India   0.0 -0.266667  -0.1 -0.300000 -0.40  -0.4  -0.4
2    Russian Federation   1.2  3.400000   3.2  2.500000  3.20   2.5   1.3
3               Germany   4.3  6.600000   1.8  4.033333  0.10   4.8   6.6
4               Algeria  -0.8 -0.900000  -1.1 -1.300000 -0.85  -0.8  -0.2
..                  ...   ...       ...   ...       ...   ...   ...   ...
186                Mali -12.1 -3.800000  -2.8 -1.100000 -1.40  -3.7  -2.1
187          Costa Rica   1.2  4.200000   4.8  2.000000  1.40   0.8   0.8
188              Norway   1.8  2.200000   2.7  3.000000  6.90   8.8   5.3
189          Tajikistan  -1.3 -3.900000  -7.9 -4.500000 -4.10  -3.4  -2.2
190              Angola   3.5  2.200000   2.6  2.900000  3.30   1.3   0.2

[185 rows x 8 columns]

<div dir=rtl id="start" style="direction:rtl;text-align: justify;line-height:200%;">
	<font face="vazir" size=3>
        بعد از اتمام هر دو مرحله‌ی پیش‌پردازش، تعداد مقادیر گم‌شده همه‌ی ستون‌ها باید 0 باشد.
    </font>
</div>

In [48]:
df.isna().sum()

Country    0
1990       0
1995       0
2000       0
2005       0
2010       0
2015       0
2020       0
dtype: int64

<div dir=rtl id="start" style="direction:rtl;text-align: justify;line-height:200%;">
	<font face="vazir" size=3>
        <span color=”purple”><b>توجه: </b></span> 
        متغیر <code>df</code> مورد داوری قرار خواهد گرفت، بنابراین به‌غیر از دو گام پیش‌پردازشی، هیچ‌گونه تغییری روی آن اعمال نکنید!
    </font>
</div>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش دوم : تحلیل
</font>
</h2>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
پس از اینکه دو مرحله‌ی بالا را انجام دادید به سوالات زیر پاسخ دهید.
    <br>
    قصد داریم با پاسخ به سوالات زیر، شهود دقیقی نسبت به وضع مهاجرت در برخی کشور‌ها به‌دست آوریم.
</font>
</div>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال اول
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در سال ۲۰۲۰، <b>اسم</b> سه کشوری که بیشترین نرخ پذیرش مهاجر را دارند پیدا کنید. جواب خود را درون لیست <code>top_countries</code> ذخیره کنید. عنصر اول، دوم و سوم این لیست به ترتیب کشورهایی هستند که در رتبه‌ی اول تا سوم جذب مهاجر قرار می‌گیرند.
</font>
</div>

In [32]:
# TODO: find the top 3 countries
top_countries1 = df.iloc[df['2020'].argsort()[:-4:-1]]
print(top_countries1)
top_countries = top_countries1['Country'].tolist()
print(top_countries)

      Country  1990  1995  2000  2005  2010  2015  2020
73    Bahrain   5.6  24.5  12.8  40.0  51.1   6.4  31.1
107  Maldives  -2.5  -2.6  -0.8  11.6  10.5  28.4  22.8
76       Oman   1.3  10.4 -17.3   1.3  19.2  48.5  18.6
['Bahrain', 'Maldives', 'Oman']

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال دوم
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    میانگین نرخ مهاجرت کشور ایران در این بازه‌ی ۳۰ ساله را محاسبه کرده و جواب را در متغیر <code>iran_mean</code> بنویسید. جنس این متغیر باید <code>numpy.float64</code> باشد.
    <br>
    اسم کشور ایران در این مجموعه‌داده به صورت <code>Iran (Islamic Republic of)</code> آمده‌ است.
</font>
</div>

In [33]:
# TODO: find iran_mean
iran = df[df['Country'] == 'Iran (Islamic Republic of)']
print(iran)

iran_mean = iran.drop(['Country'],axis=1).apply(lambda x: x.mean(), axis=1).astype(np.float64)
print(iran_mean)

                       Country  1990  1995  2000  2005  2010  2015  2020
39  Iran (Islamic Republic of)   5.8  -3.0  -0.7  -0.1  -1.6  -1.3  -0.7
39   -0.228571
dtype: float64

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال سوم
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    <b>اسم</b> کشوری که در این بازه‌ی ۳۰ ساله، بیشترین رشد را داشته است در متغیر <code>highest_growth</code> بنویسید. این متغیر از نوع <i>str</i> است. منظور از رشد، تفاضل نرخ سال ۲۰۲۰ از سال ۱۹۹۰ است.

</font>
</div>

In [34]:
# TODO: find highest_growth
df_copy = df.copy()
df_copy['Differences'] = df_copy['2020'] - df_copy['1990']
print(df_copy['Differences'].max())
print(df_copy['Differences'])

highest_growth_indx = df_copy.index[df_copy['Differences'] == df_copy['Differences'].max()].to_numpy()
print('-------')
highest_growth = df.at[highest_growth_indx[0],'Country']
print(highest_growth)

33.1
0       0.2
1      -0.4
2       0.1
3       2.3
4       0.6
       ...
186    10.0
187    -0.4
188     3.5
189    -0.9
190    -3.3
Name: Differences, Length: 185, dtype: float64
-------
Liberia

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [49]:
# DO NOT CHANGE THIS CELL !
import zipfile
import joblib

df.to_csv('./df.csv', index=False)
joblib.dump(top_countries,"top_countries")
joblib.dump(iran_mean,"iran_mean")
joblib.dump(highest_growth, "highest_growth")


def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)


file_names = ["df.csv", "top_countries", "iran_mean", "highest_growth", "to_stay_or_not_to_stay.ipynb"]
compress(file_names)

File Paths:
['df.csv', 'top_countries', 'iran_mean', 'highest_growth', 'to_stay_or_not_to_stay.ipynb']

In [40]:
# Calculate the mean of each row
row_means1 = df.apply(lambda x: x.mean(), axis=1).astype('float16')
print(row_means1)
# Replace NaN values with the mean of each row

# df_filled = df.apply(lambda row: row.fillna(row_means1.loc[row.index]), axis=1)
df_filled = df.apply(lambda row: row.fillna(row_means1[row.name]), axis=1)
df_filled

0    1.000000
1    2.666016
2         NaN
3    3.500000
dtype: float16

     A    B         C    D
0  1.0  2.0  1.000000  0.0
1  3.0  4.0  2.666016  1.0
2  NaN  NaN       NaN  NaN
3  3.5  3.0  3.500000  4.0